## Implementing Neural Networks from Scratch

### Part 1: Coding Neurons and Layers

In [1]:
# Coding our first neuron with 3 inputs

inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias)

print(output)

2.3


In [2]:
# Coding our second neuron with 4 inputs

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = (
    inputs[0] * weights[0] + inputs[1] * weights[1] +
    inputs[2] * weights[2] + inputs[3] * weights[3] + bias
)

print(output)

4.8


In [3]:
# Coding our first layer 

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

weights1 = weights[0]   # List of all weights associated with 1st Neuron: W11, W12, W13, W14
weights2 = weights[1]   # List of all weights associated with 2nd Neuron: W21, W22, W23, W24
weights3 = weights[2]   # List of all weights associated with 3rd Neuron: W31, W32, W33, W34

output = [
    # Neuron 1
    inputs[0] * weights1[0] + 
    inputs[1] * weights1[1] +
    inputs[2] * weights1[2] +
    inputs[3] * weights1[3] + biases[0],

    # Neuron 2
    inputs[0] * weights2[0] + 
    inputs[1] * weights2[1] +
    inputs[2] * weights2[2] +
    inputs[3] * weights2[3] + biases[1],

    # Neuron 3
    inputs[0] * weights3[0] + 
    inputs[1] * weights3[1] +
    inputs[2] * weights3[2] +
    inputs[3] * weights3[3] + biases[2],
]

print(output)

[4.8, 1.21, 2.385]


```
output = summation of (inputs * weights) + bias

output = (w1x1 + w2x2 + w3x3 + b)
```

In [4]:
# Using loops for better and easier coding

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_outputs = [] # output for current layer

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 # Placeholder output variable
    
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight and add to the neuron's output variable
        neuron_output += n_input * weight
    neuron_output += neuron_bias # Adding bias 
    
    layer_outputs.append(neuron_output)

print(layer_outputs)



[4.8, 1.21, 2.385]


### Part 2: Using Numpy to Code Neurons and Layers

####  Rules of Matrix Multiplication:
1. The **number of columns** in the first matrix must equal the **number of rows** in the second matrix.  
   - If `A` is (m × n) and `B` is (n × p), then `A × B` is defined.

2. The result will be a matrix of size **(m × p)**.

3. Each element in the result is computed by the **dot product** of a row from `A` and a column from `B`.


#### Rules of Dot Products

1. The dot product between a vector A and vector B,    `np.dot(A, B) == np.dot(B, A)`

2. The dot product between a vector A and matrix B,    `np.dot(A, B) != np.dot(B, A)`

3. The dot product between a matrix A and matrix B,    `np.dot(A, B) == A X B`

In [3]:
# Coding a neuron using NumPy

import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


In [4]:
# Coding layers using NumPy

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vector results in a list of dot products. 
# The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other vector

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


In [12]:
# Coding layers of neurons and batch of data using NumPy

inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

# We cannot tranpose lists in Python, so we have to convert the lists into an array first.

outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [14]:
# 2 layers and batch of data using NumPy

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Calculating the output of the first layer

layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1

# Calculating the output of the second layer

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
